### ISSUE TITLE
Make Tega's GIF smaller

### ISSUE THREAD

**Issue by olofster** [huertanix/arthackday-web#206]
Right now it's 5.6MB. We should at least get it down to 2MB if not 1MB(?)

Who has the raw file?

**Comment by olofster** [comment]
barely loads on my mobile

**Comment by huertanix** [comment]
Just asked Tega to make it smaller. Side note: Afterglow's gif is still 21 MB.

**Comment by olofster** [comment]
damn that is absurd. Thought we fixed that a while ago.
ok whatever then I guess:)

**Comment by jedahan** [comment]
maaaybe thing of trying http://gfycat.com/ ?
cuz mp4s are much smaller than gifs nowadays?

**Comment by jedahan** [comment]
Afterglow, gifycat'd http://gfycat.com/BraveSelfreliantGalapagosdove 21Mb->4Mb

**Comment by olofster** [comment]
Awesome want to send a PR

**Comment by jedahan** [comment]
Yeah i'll look into how to embed the video this afternoon
